### ISSUE TITLE
Hello! What can I help you?

### ISSUE THREAD

**Issue by anstak** [boxsnake-php/simple-api-ssr#1]
Hello! I want to create simple framework for react app. What do you do here?

**Comment by boxsnake** [comment]
* This is a php-written simple framework.
* This framework reads data from api(s), and then fill data into templates to enable server side rendering.
* By doing these, you can keep your apis separate from your pages rendering.
* Unlike common PHP frameworks such as Symfony and Laravel, it does not tweak into the main api framework router to enable http access to pages.
* This is quite different from the react framework. React app framework is a pre-designed project structure which is reproducible.
